"""add_team_names_and_winner_to_games

Revision ID: 0d7fa65faeff
Revises: 56de119416c1
Create Date: 2025-11-25 06:12:04.013706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d7fa65faeff'
down_revision: Union[str, None] = '56de119416c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('home_team_name', sa.String(), nullable=True))
    op.add_column('games', sa.Column('away_team_name', sa.String(), nullable=True))
    op.add_column('games', sa.Column('winner_team_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('winner_team_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'games', 'teams', ['winner_team_id'], ['id'])
    op.create_index(op.f('ix_stats_features_id'), 'stats_features', ['id'], unique=False)
    
    # Populate team names from teams table
    op.execute("""
        UPDATE games
        SET home_team_name = teams.name
        FROM teams
        WHERE games.home_team_id = teams.id
    """)
    
    op.execute("""
        UPDATE games
        SET away_team_name = teams.name
        FROM teams
        WHERE games.away_team_id = teams.id
    """)
    
    # Populate winner information (only for completed games with different scores)
    op.execute("""
        UPDATE games
        SET winner_team_id = home_team_id,
            winner_team_name = home_team_name
        WHERE home_score > away_score
    """)
    
    op.execute("""
        UPDATE games
        SET winner_team_id = away_team_id,
            winner_team_name = away_team_name
        WHERE away_score > home_score
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stats_features_id'), table_name='stats_features')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'winner_team_name')
    op.drop_column('games', 'winner_team_id')
    op.drop_column('games', 'away_team_name')
    op.drop_column('games', 'home_team_name')
    # ### end Alembic commands ###
