"""add_player_position_and_reorder_defensive_stats

Revision ID: 2372dbebac6b
Revises: a6d3f0225ad1
Create Date: 2025-11-25 18:49:12.101397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2372dbebac6b'
down_revision: Union[str, None] = 'a6d3f0225ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_stats', sa.Column('player_position', sa.String(), nullable=True))
    op.add_column('stats_features', sa.Column('player_position', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stats_features', 'player_position')
    op.drop_column('player_stats', 'player_position')
    # ### end Alembic commands ###
