"""add_player_name_to_injuries

Revision ID: 2a51173fa744
Revises: e82894f1430f
Create Date: 2025-11-25 05:49:55.312310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a51173fa744'
down_revision: Union[str, None] = 'e82894f1430f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('injuries', sa.Column('player_name', sa.String(), nullable=True))
    
    # Populate existing records with player names from the players table
    op.execute("""
        UPDATE injuries
        SET player_name = players.name
        FROM players
        WHERE injuries.player_id = players.id
    """)
    
    # Now set column to NOT NULL
    op.alter_column('injuries', 'player_name', nullable=False)
    
    op.create_index(op.f('ix_player_stats_id'), 'player_stats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_stats_id'), table_name='player_stats')
    op.drop_column('injuries', 'player_name')
    # ### end Alembic commands ###
