"""add_player_name_to_stats_features

Revision ID: 56de119416c1
Revises: 2821b8d805ba
Create Date: 2025-11-25 06:02:11.672068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56de119416c1'
down_revision: Union[str, None] = '2821b8d805ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('injuries', 'date_reported',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_injuries_id'), 'injuries', ['id'], unique=False)
    
    # Drop old stats_features table (old design was per-game, new design is per-player)
    op.drop_table('stats_features')
    
    # Create new stats_features table with simplified schema (one row per player)
    op.execute("""
        CREATE TABLE stats_features (
            id SERIAL PRIMARY KEY,
            player_id INTEGER NOT NULL UNIQUE REFERENCES players(id),
            player_name VARCHAR NOT NULL,
            season INTEGER NOT NULL DEFAULT 2024,
            games_played INTEGER DEFAULT 0,
            avg_passing_yards FLOAT DEFAULT 0,
            avg_passing_tds FLOAT DEFAULT 0,
            avg_rushing_yards FLOAT DEFAULT 0,
            avg_rushing_tds FLOAT DEFAULT 0,
            avg_receiving_yards FLOAT DEFAULT 0,
            avg_receiving_tds FLOAT DEFAULT 0,
            avg_receptions FLOAT DEFAULT 0,
            avg_targets FLOAT DEFAULT 0,
            total_yards FLOAT DEFAULT 0,
            total_tds FLOAT DEFAULT 0,
            last_3_avg_yards FLOAT DEFAULT 0,
            last_3_avg_tds FLOAT DEFAULT 0,
            consistency_score FLOAT DEFAULT 0,
            home_avg_yards FLOAT DEFAULT 0,
            away_avg_yards FLOAT DEFAULT 0,
            avg_target_share FLOAT DEFAULT 0,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITH TIME ZONE
        )
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop new stats_features table
    op.drop_table('stats_features')
    
    # Recreate old stats_features table structure
    op.execute("""
        CREATE TABLE stats_features (
            id SERIAL PRIMARY KEY,
            player_id INTEGER NOT NULL REFERENCES players(id),
            game_id INTEGER NOT NULL REFERENCES games(id),
            avg_yards_3g FLOAT,
            avg_yards_5g FLOAT,
            avg_yards_10g FLOAT,
            avg_receptions_3g FLOAT,
            avg_targets_3g FLOAT,
            avg_touchdowns_3g FLOAT,
            trend_slope FLOAT,
            consistency_score FLOAT,
            target_share FLOAT,
            snap_percentage FLOAT,
            red_zone_usage FLOAT,
            home_avg_yards FLOAT,
            away_avg_yards FLOAT,
            opponent_rank_vs_position INTEGER,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITH TIME ZONE
        )
    """)
    
    op.drop_index(op.f('ix_injuries_id'), table_name='injuries')
    op.alter_column('injuries', 'date_reported',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
