"""add_defensive_stats_columns

Revision ID: a6d3f0225ad1
Revises: 5efe4f23e531
Create Date: 2025-11-25 18:35:06.403148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6d3f0225ad1'
down_revision: Union[str, None] = '5efe4f23e531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('games_new_espn_game_id_key1', 'games', type_='unique')
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.add_column('player_stats', sa.Column('tackles_total', sa.Integer(), nullable=True))
    op.add_column('player_stats', sa.Column('tackles_solo', sa.Integer(), nullable=True))
    op.add_column('player_stats', sa.Column('tackles_for_loss', sa.Integer(), nullable=True))
    op.add_column('player_stats', sa.Column('sacks', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('qb_hits', sa.Integer(), nullable=True))
    op.add_column('player_stats', sa.Column('interceptions_def', sa.Integer(), nullable=True))
    op.add_column('player_stats', sa.Column('pass_deflections', sa.Integer(), nullable=True))
    op.add_column('player_stats', sa.Column('forced_fumbles', sa.Integer(), nullable=True))
    op.add_column('player_stats', sa.Column('fumble_recoveries', sa.Integer(), nullable=True))
    op.add_column('player_stats', sa.Column('defensive_tds', sa.Integer(), nullable=True))
    op.add_column('player_stats', sa.Column('safeties', sa.Integer(), nullable=True))
    op.add_column('stats_features', sa.Column('avg_tackles', sa.Float(), nullable=True))
    op.add_column('stats_features', sa.Column('avg_sacks', sa.Float(), nullable=True))
    op.add_column('stats_features', sa.Column('avg_interceptions', sa.Float(), nullable=True))
    op.add_column('stats_features', sa.Column('avg_pass_deflections', sa.Float(), nullable=True))
    op.add_column('stats_features', sa.Column('avg_tackles_for_loss', sa.Float(), nullable=True))
    op.add_column('stats_features', sa.Column('total_tackles', sa.Integer(), nullable=True))
    op.add_column('stats_features', sa.Column('total_sacks', sa.Float(), nullable=True))
    op.add_column('stats_features', sa.Column('total_interceptions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stats_features', 'total_interceptions')
    op.drop_column('stats_features', 'total_sacks')
    op.drop_column('stats_features', 'total_tackles')
    op.drop_column('stats_features', 'avg_tackles_for_loss')
    op.drop_column('stats_features', 'avg_pass_deflections')
    op.drop_column('stats_features', 'avg_interceptions')
    op.drop_column('stats_features', 'avg_sacks')
    op.drop_column('stats_features', 'avg_tackles')
    op.drop_column('player_stats', 'safeties')
    op.drop_column('player_stats', 'defensive_tds')
    op.drop_column('player_stats', 'fumble_recoveries')
    op.drop_column('player_stats', 'forced_fumbles')
    op.drop_column('player_stats', 'pass_deflections')
    op.drop_column('player_stats', 'interceptions_def')
    op.drop_column('player_stats', 'qb_hits')
    op.drop_column('player_stats', 'sacks')
    op.drop_column('player_stats', 'tackles_for_loss')
    op.drop_column('player_stats', 'tackles_solo')
    op.drop_column('player_stats', 'tackles_total')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.create_unique_constraint('games_new_espn_game_id_key1', 'games', ['espn_game_id'])
    # ### end Alembic commands ###
