"""add player name to stats

Revision ID: d8f0253c7110
Revises: 03d56304834f
Create Date: 2025-11-25 05:30:48.559734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8f0253c7110'
down_revision: Union[str, None] = '03d56304834f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_stats', sa.Column('player_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_stats', 'player_name')
    # ### end Alembic commands ###
